/**
 * phase3-9371-85244.figma.js — Phase 3 targeted write
 *
 * Generated by MIMR for run: odin-20260702-113054
 * Target: _priv.Bonus Bar (9371:85244) in file Ahvbwk0dUHeHazrQX2XtGd
 *
 * Applies 11 approved token bindings across 5 nodes.
 * Uses direct node-ID targeting (targeted-script path for fills, per lesson).
 * Helpers mirror bulk-update.figma.js patterns.
 *
 * HOW TO RUN:
 *   1. Open the Figma file Ahvbwk0dUHeHazrQX2XtGd in Figma
 *   2. Open Plugins → Development → Open Console (or run via mcp_figma_use_figma)
 *   3. Paste the full script content and execute
 *   OR use mcp_figma_use_figma with fileKey="Ahvbwk0dUHeHazrQX2XtGd"
 */

const TS_NS = 'tokens';

// ─── Write plan (approved) ────────────────────────────────────────────────────
// 9371:85244  paddingLeft + paddingRight → spacing/fds-spacing-const/container/fds-spacing-const-container-canvas-lg
// 9371:85244  cornerRadius               → fds-round/fds-round-150
// 9371:85245  fills[0]                   → var/fds/fds-info
// 9371:85245  strokes[0] color           → var/fds/fds-on-surface-ulow
// 9371:85245  strokeWeight (all 4)       → fds-stroke/fds-stroke-100
// 9371:85245  padding (all 4)            → spacing/fds-spacing/fds-spacing-200
// 9371:85245  cornerRadius               → fds-round/fds-round-150
// 9371:85247  itemSpacing                → spacing/fds-spacing/fds-spacing-050
// 9371:85248  typography                 → Paragraphs/fds/fds-paragraphs-small
// 9371:85248  fills[0]                   → var/fds/fds-on-info-alternate
// 9371:85249  typography                 → Paragraphs/fds/fds-paragraphs-regular-bold
// 9371:85249  fills[0]                   → var/fds/fds-on-info-alternate

// ─── Helpers (mirrored from bulk-update.figma.js) ────────────────────────────

/** Parse CSS color → { r, g, b, a } (0-1 range). */
function parseCssColor(str) {
  const rgba = str.match(/rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)(?:\s*,\s*([\d.]+))?\s*\)/);
  if (rgba) {
    return {
      r: parseFloat(rgba[1]) / 255, g: parseFloat(rgba[2]) / 255,
      b: parseFloat(rgba[3]) / 255, a: rgba[4] !== undefined ? parseFloat(rgba[4]) : 1,
    };
  }
  const hex = str.match(/^#([0-9a-fA-F]{3,8})$/);
  if (hex) {
    let h = hex[1];
    if (h.length === 3) h = h.split('').map(c => c + c).join('');
    return {
      r: parseInt(h.slice(0,2),16)/255, g: parseInt(h.slice(2,4),16)/255,
      b: parseInt(h.slice(4,6),16)/255, a: h.length===8 ? parseInt(h.slice(6,8),16)/255 : 1,
    };
  }
  return null;
}

// ─── Resolution (one-time loads) ─────────────────────────────────────────────

// Fetch all target nodes in parallel (amortise getNodeByIdAsync cost)
const TARGET_IDS = ['9371:85244', '9371:85245', '9371:85247', '9371:85248', '9371:85249'];
const [nodesArr, allVars, allTextStyles] = await Promise.all([
  Promise.all(TARGET_IDS.map(id => figma.getNodeByIdAsync(id))),
  figma.variables.getLocalVariablesAsync(),
  figma.getLocalTextStylesAsync(),
]);

const nodeById = {};
nodesArr.forEach((n, i) => { if (n) nodeById[TARGET_IDS[i]] = n; });

const varByName = new Map(allVars.map(v => [v.name, v]));
const textStyleByName = new Map(allTextStyles.map(s => [s.name, s]));

// ─── Report ───────────────────────────────────────────────────────────────────

const report = [];
let applied = 0, failed = 0;

function ok(entry)  { applied++; report.push({ status: 'ok',    ...entry }); }
function err(entry) { failed++;  report.push({ status: 'error', ...entry }); }

// ─── Write helpers ────────────────────────────────────────────────────────────

/** Write TS metadata key. */
function writeTS(node, key, tsPath) {
  node.setSharedPluginData(TS_NS, key, JSON.stringify(tsPath));
}

/** Bind scalar NV (setBoundVariable) + TS metadata. Falls back to rawValue if var not found. */
function bindScalar(node, props, nvName, tsKey, tsPath, rawValue) {
  const v = varByName.get(nvName);
  if (v) {
    for (const prop of props) {
      try {
        node.setBoundVariable(prop, v);
        ok({ nodeId: node.id, type: 'nv-scalar', prop, varId: v.id, varName: v.name });
      } catch(e) {
        err({ nodeId: node.id, type: 'nv-scalar', prop, nvName, error: e.message });
      }
    }
  } else if (rawValue !== undefined) {
    // Raw fallback
    for (const prop of props) {
      try {
        node[prop] = rawValue;
        ok({ nodeId: node.id, type: 'raw-scalar', prop, rawValue });
      } catch(e) {
        err({ nodeId: node.id, type: 'raw-scalar', prop, error: e.message });
      }
    }
  } else {
    err({ nodeId: node.id, type: 'nv-scalar', props, nvName, error: 'variable not found, no rawValue' });
  }
  if (tsKey) writeTS(node, tsKey, tsPath);
}

/** Bind fill NV via setBoundVariableForPaint (targeted script path). */
function bindFill(node, nvName, tsPath, rawHex) {
  writeTS(node, 'fill', tsPath);
  const v = varByName.get(nvName);
  if (v) {
    try {
      const fills = (node.fills && node.fills.length > 0)
        ? JSON.parse(JSON.stringify(node.fills))
        : [{ type: 'SOLID', color: { r: 0, g: 0, b: 0 }, opacity: 1 }];
      fills[0] = figma.variables.setBoundVariableForPaint(fills[0], 'color', v);
      node.fills = fills;
      ok({ nodeId: node.id, type: 'nv-fill', varId: v.id, varName: v.name });
    } catch(e) {
      err({ nodeId: node.id, type: 'nv-fill', nvName, error: e.message });
    }
  } else if (rawHex) {
    // Raw color fallback
    try {
      const color = parseCssColor(rawHex);
      if (color) {
        const { a, ...rgb } = color;
        node.fills = [{ type: 'SOLID', color: rgb, opacity: a }];
        ok({ nodeId: node.id, type: 'raw-fill', rawHex });
      }
    } catch(e) {
      err({ nodeId: node.id, type: 'raw-fill', rawHex, error: e.message });
    }
  } else {
    err({ nodeId: node.id, type: 'nv-fill', nvName, error: 'variable not found, no rawHex' });
  }
}

/** Bind stroke color NV via setBoundVariableForPaint. */
function bindStrokeColor(node, nvName, tsPath) {
  writeTS(node, 'borderColor', tsPath);
  const v = varByName.get(nvName);
  if (!v) { err({ nodeId: node.id, type: 'nv-stroke-color', nvName, error: 'variable not found' }); return; }
  try {
    const strokes = (node.strokes && node.strokes.length > 0)
      ? JSON.parse(JSON.stringify(node.strokes))
      : [{ type: 'SOLID', color: { r: 0, g: 0, b: 0 }, opacity: 1 }];
    strokes[0] = figma.variables.setBoundVariableForPaint(strokes[0], 'color', v);
    node.strokes = strokes;
    ok({ nodeId: node.id, type: 'nv-stroke-color', varId: v.id, varName: v.name });
  } catch(e) {
    err({ nodeId: node.id, type: 'nv-stroke-color', nvName, error: e.message });
  }
}

/** Bind text style (textStyleId) + TS metadata. Assign before fill (per lesson). */
function bindTextStyle(node, tsPath) {
  writeTS(node, 'typography', tsPath);
  const slashName = tsPath.replace(/\./g, '/');
  const s = textStyleByName.get(slashName);
  if (!s) { err({ nodeId: node.id, type: 'text-style', slashName, error: 'style not found' }); return; }
  try {
    node.textStyleId = s.id;
    ok({ nodeId: node.id, type: 'text-style', styleId: s.id, styleName: s.name });
  } catch(e) {
    err({ nodeId: node.id, type: 'text-style', slashName, error: e.message });
  }
}

// ─── Writes ───────────────────────────────────────────────────────────────────

// ── Node 9371:85244 — _priv.Bonus Bar ────────────────────────────────────────
const n44 = nodeById['9371:85244'];
if (!n44) {
  err({ nodeId: '9371:85244', error: 'node not found' });
} else {
  const SPACING_CANVAS_LG_NV = 'spacing/fds-spacing-const/container/fds-spacing-const-container-canvas-lg';
  const SPACING_CANVAS_LG_TS = 'spacing.fds-spacing-const.container.fds-spacing-const-container-canvas-lg';
  bindScalar(n44, ['paddingLeft'],  SPACING_CANVAS_LG_NV, 'paddingLeft',  SPACING_CANVAS_LG_TS, 20);
  bindScalar(n44, ['paddingRight'], SPACING_CANVAS_LG_NV, 'paddingRight', SPACING_CANVAS_LG_TS, 20);

  // cornerRadius — single call binds all 4 corners (lesson: 5x faster)
  bindScalar(n44, ['cornerRadius'], 'fds-round/fds-round-150', 'borderRadius', 'fds-round.fds-round-150', 12);
}

// ── Node 9371:85245 — inner container ────────────────────────────────────────
const n45 = nodeById['9371:85245'];
if (!n45) {
  err({ nodeId: '9371:85245', error: 'node not found' });
} else {
  // fills[0] → fds-info (targeted fill NV path)
  bindFill(n45, 'var/fds/fds-info', 'var.fds.fds-info', '#608DF2');

  // strokes[0] color → fds-on-surface-ulow
  bindStrokeColor(n45, 'var/fds/fds-on-surface-ulow', 'var.fds.fds-on-surface-ulow');

  // strokeWeight (all 4 sides) → fds-stroke-100
  writeTS(n45, 'borderWidth', 'fds-stroke.fds-stroke-100');
  bindScalar(n45,
    ['strokeTopWeight','strokeBottomWeight','strokeLeftWeight','strokeRightWeight'],
    'fds-stroke/fds-stroke-100', null, null, 1);

  // padding (all 4) → fds-spacing-200
  const SP200_NV = 'spacing/fds-spacing/fds-spacing-200';
  const SP200_TS = 'spacing.fds-spacing.fds-spacing-200';
  bindScalar(n45, ['paddingTop'],    SP200_NV, 'paddingTop',    SP200_TS, 16);
  bindScalar(n45, ['paddingRight'],  SP200_NV, 'paddingRight',  SP200_TS, 16);
  bindScalar(n45, ['paddingBottom'], SP200_NV, 'paddingBottom', SP200_TS, 16);
  bindScalar(n45, ['paddingLeft'],   SP200_NV, 'paddingLeft',   SP200_TS, 16);

  // cornerRadius → fds-round-150
  bindScalar(n45, ['cornerRadius'], 'fds-round/fds-round-150', 'borderRadius', 'fds-round.fds-round-150', 12);
}

// ── Node 9371:85247 — icon row ────────────────────────────────────────────────
const n47 = nodeById['9371:85247'];
if (!n47) {
  err({ nodeId: '9371:85247', error: 'node not found' });
} else {
  bindScalar(n47, ['itemSpacing'],
    'spacing/fds-spacing/fds-spacing-050', 'itemSpacing', 'spacing.fds-spacing.fds-spacing-050', 4);
}

// ── Node 9371:85248 — text (small) ────────────────────────────────────────────
const n48 = nodeById['9371:85248'];
if (!n48) {
  err({ nodeId: '9371:85248', error: 'node not found' });
} else {
  // Assign textStyleId BEFORE fill (per lesson: avoid ordering issues)
  bindTextStyle(n48, 'Paragraphs.fds.fds-paragraphs-small');
  bindFill(n48, 'var/fds/fds-on-info-alternate', 'var.fds.fds-on-info-alternate', '#ffffff');
}

// ── Node 9371:85249 — text (regular-bold) ─────────────────────────────────────
const n49 = nodeById['9371:85249'];
if (!n49) {
  err({ nodeId: '9371:85249', error: 'node not found' });
} else {
  // Assign textStyleId BEFORE fill
  bindTextStyle(n49, 'Paragraphs.fds.fds-paragraphs-regular-bold');
  bindFill(n49, 'var/fds/fds-on-info-alternate', 'var.fds.fds-on-info-alternate', '#ffffff');
}

// ─── Summary ──────────────────────────────────────────────────────────────────
return JSON.stringify({ applied, failed, report }, null, 2);
